databases:
  - name: schoolapp
    databaseName: schoolapp
    user: schoolapp

services:
  - type: web
    name: schoolapp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: schoolapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
